variables:
  DOCKER_REGISTRY: docker-dev-snapshot-local.logistics.corp
  ELASSANDRA_VERSION: 6.2.3.39
  ELASSANDRA_COMMIT: a1248f22

stages:
 - download
 - publish

# Download Elassandra tar.gz
download:
  stage: download
  image: curlimages/curl:latest
  script:
    - |
      curl -k --header "JOB-TOKEN: ${CI_JOB_TOKEN}" "https://gitlab.logistics.corp/api/v4/projects/8319/packages/elassandra-${ELASSANDRA_VERSION}.tar.gz" -o "elassandra-${ELASSANDRA_VERSION}.tar.gz"
  artifacts:
    paths:
      - elassandra-${ELASSANDRA_VERSION}.tar.gz
  tags:
    - k8s-iah-east

publish:
  stage: publish
  image: docker-dev-snapshot-local.logistics.corp/strapdata/elassandra_builder:latest
  services:
   - name: docker:dind
     alias: dockerdaemon
     command: ["--mtu=1440"]
  variables:
    DOCKER_BUILD_OPTS: --network host --build-arg no_proxy=".logistics.corp,dockerdaemon" --build-arg http_proxy="http://iahlproxy.logistics.corp:3128" --build-arg https_proxy="http://iahlproxy.logistics.corp:3128" --rm
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $DOCKER_USERNAME -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY
  script:
    - BASE_IMAGE_TAG=${ELASSANDRA_VERSION} PACKAGE_LOCATION=elassandra-${ELASSANDRA_VERSION}.tar.gz DOCKER_PUBLISH=true ./build.sh
  tags:
    - k8s-iah-east
