variables:
  DOCKER_REGISTRY: docker-dev-snapshot-local.logistics.corp
  ELASSANDRA_VERSION: 6.2.3.39
  ELASSANDRA_COMMIT: a1248f22

stages:
 - download
 - publish

# Download Elassandra tar.gz
download:
  stage: download
  image: curlimages/curl:latest
  script:
    - |
      curl -k --header "JOB-TOKEN: ${CI_JOB_TOKEN}" "https://gitlab.logistics.corp/api/v4/projects/8319/packages/elassandra-${ELASSANDRA_VERSION}.deb" -o "elassandra-${ELASSANDRA_VERSION}.deb"
  artifacts:
    paths:
      - elassandra-${ELASSANDRA_VERSION}.deb
  tags:
    - k8s-iah-east

publish:
  stage: publish
  image: docker-dev-snapshot-local.logistics.corp/strapdata/elassandra_builder:latest
  services:
   - name: docker:dind
     alias: dockerdaemon
     command: ["--mtu=1440"]
  variables:
    http_proxy: http://iahlproxy.logistics.corp:3128
    https_proxy: http://iahlproxy.logistics.corp:3128
    no_proxy: ".logistics.corp,dockerdaemon"
    DOCKER_BUILD_OPTS: --network host --build-arg no_proxy=${no_proxy} --build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy} --rm
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_DRIVER: overlay2
  before_script:
    - mkdir -p $HOME/.docker/
    - 'echo "{ \"proxies\": { \"default\": { \"httpProxy\": \"$http_proxy\", \"httpsProxy\": \"$https_proxy\", \"noProxy\": \"$no_proxy\" } } }" > $HOME/.docker/config.json'
    - docker login -u $DOCKER_USERNAME -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY
  script:
    - BASE_IMAGE_TAG=${ELASSANDRA_VERSION} PACKAGE_LOCATION=elassandra-${ELASSANDRA_VERSION}.deb DOCKER_PUBLISH=true ./build.sh
  tags:
    - k8s-iah-east
